name: Pull Request Merge Comment

on:
  pull_request_target:
    types:
      - "closed"
    branches:
      - "master"

permissions:
  issues: write
  pull-requests: write

jobs:
  comment_on_merge:
    if: github.repository == 'codinasion/README' && github.event.pull_request.merged && github.event.pull_request.base.ref == github.event.repository.default_branch && github.event.pull_request.user.login != 'harshraj8843'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body: `Thanks very much for contributing!

              Your pull request has been merged 🎉 You should see your changes appear on the site in approximately 24 hours. 

              Support this project by giving it a star ⭐.

              [Join Our Community](https://github.com/codinasion/.github/issues/new?assignees=&labels=welcome+🎉🎉🎉&template=invitation.yml&title=Please+invite+me+to+Codinasion)

              If you're looking for your next contribution, check out our [help wanted issues](https://github.com/search?q=is%3Aopen+label%3A%22help+wanted%22+user%3Acodinasion&type=Issues) :zap:`
            })
